# evaluate on govreport
tag: summ_nnl

# model settings
model_class: vanilla
model_name_or_path: meta-llama/Llama-2-7b-chat-hf
output_dir: output/Llama-2-7b-chat-hf

# data settings
datasets: govreport
demo_files: ''
test_files: ''

max_test_samples: 500
seed: 42

# evaluation settings
shot: 0
n_shot_encoder: 0
n_shot_decoder: 0

n_demo_doc: 0
n_test_doc: 1
n_test_doc_encoder: 0
n_test_doc_decoder: 1
include_title: true 
use_instruction: true
context_strategy: concat-truncate_left

# generation settings
input_max_length: 2048
generation_max_length: 1024
generation_min_length: 10
context_max_length: 256
temperature: 1.0
top_p: 0.95
do_sample: true
